# Site settings

title: Microparticle Distribution in Cellulose Acetate Membranes Manufactured Using Slot-Die Extrusion

header-img: img/reconstructed_2.png
email: ethan.clark.hilton@gatech.edu
email: pgriffiths3@gatech.edu
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/Microparticle-distribution"
url: "http://ehilton3.github.io"
github_username:  ehilton3
project_repository: Microparticle-distribution
disqus_shortname: Microparticle-distribution

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
