# Site settings

title: Microparticle Distribution in Slot-Die Extrusion Membranes

header-img: img/reconstructed_2.png
email: ethan.clark.hilton@gatech.edu
email: pgriffiths3@gatech.edu
description: "Exploring the effects of changes during the slot-die extrusion manufacturing process on the microparticle distribution in cellulose acetate membranes."
baseurl: "/MIC-Microparticle-distribution"
url: "http://Materials-Informatics-Class-Fall2015.github.io"
github_username:  ehilton3
project_repository: MIC-Microparticle-distribution
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
