# Site settings

<<<<<<< HEAD
title: Microparticle Distribution in Cellulose Acetate Membranes Manufactured Using Slot-Die Extrusion 
=======
title: Microparticle Distribution in Cellulose Acetate Membranes Manufactured Using Slot-Die Extrusion
>>>>>>> origin/gh-pages
header-img: img/home-bg.jpg
email: ethan.clark.hilton [at] gatech.edu   pgriffiths3 [at] gatech.edu
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/project-pages"
url: "http://matin-hub.github.io"
github_username:  matin-hub
project_repository: project-pages
disqus_shortname: project-pages

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
