# Site settings

title: Microparticle Distribution in Cellulose Acetate Membranes Manufactured Using Slot-Die Extrusion

header-img: img/home-bg.jpg
email: ethan.clark.hilton@gatech.edu
email: pgriffiths3@gatech.edu
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/microparticle-distribution"
url: "http://ehilton3.github.io"
github_username:  ehilton3
project_repository: microparticle-distribution
disqus_shortname: microparticle-distribution

# Build settings
# Don't change these variables
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
